### PR TITLE
add codacy badge

### PR DESCRIPTION
**Pull request by ayan-usgs**

### CODE REVIEW

**Comment by ayan-usgs** [comment]
> It would also be good to explore setting the linters for our preferred style on Codacy. It will use standard configuration files in the repo if available.

Yep. I can take a look at that.

**Comment by ayan-usgs** [comment]
@mbucknell -- I've added configuration files for eslint and pylint.

**Comment by mbucknell** [comment]
Are these just standard settings for js and python?

**Comment by ayan-usgs** [comment]
> Are these just standard settings for js and python?

Mostly. The python config definitely is. The javascript is all of the eslint recommended stuff and one warning that I decided to include regarding brace style.

**Pull request merged**
