### PR TITLE
WDFN-9 - TravisCI / Coveralls

### PR DESCRIPTION
**Pull request by danielnaab**
This PR is dependent on unmerged WDFN-9, so includes the commits from that PR. The only relevant portion is the .travis.yml file.

I based this off the WQP one, and it wasn't clear to me how to use coveralls-lcov... I could use some help there.

### CODE REVIEW

**Comment by mbucknell** [comment]
Re coveralls-lcov. The whole after_success step finds the coverage files from the python and javascript and merges them together. I believe coveralls-lcov translates from .lcov to json, but it's been awhile.

**Comment by ayan-usgs** [comment]
> Re coveralls-lcov. The whole after_success step finds the coverage files from the python and javascript and merges them together. I believe coveralls-lcov translates from .lcov to json, but it's been awhile.

Yep. In addition, coveralls-lcov merges the coverage report from the javascript tests with those of the python tests. The merged report is then sent to coveralls. If I recall correctly, this is pertinent code in WQP's karma.conf file that generates the javascript report:

```		// available reporters: https://npmjs.org/browse/keyword/karma-reporter
		reporters: ['dots', 'coverage'],

		coverageReporter: {
			reporters: [
				{type: 'html', dir: 'coverage/'},
				{type: 'cobertura', dir: 'coverage/'},
				{type: 'lcovonly', dir: 'coverage/'}
			]
		},
```

**Comment by danielnaab** [comment]
Excellent, thank you both!

**Comment by danielnaab** [comment]
Closing to remove duplicate commits

**Pull request closed without merging**
