### PR TITLE
Updated change log.

### PR DESCRIPTION
**Pull request by mbucknell**

### CODE REVIEW

**Comment by mbucknell** [comment]
Please let me know if I'm missing something from the Changelog.

**Comment by ayan-usgs** [comment]
Hmm... not sure if these two items count as changes or additions (or if they should be included at...):

- Graphs are not shown for sites with not current times
- Parameters with no data points in current or last year data are omitted from the select table

**Comment by ayan-usgs** [comment]
Line 21 appears to be missing a bullet.

**Comment by ayan-usgs** [comment]
Also, graphs are not shown for sites with no current data.

**Comment by mbucknell** [comment]
Regarding Line 21. That's correct. Two things were done to the select a timeseries list visually.

**Pull request merged**
